-- Player Stats: per-player, per-week statistics sourced from nflverse.
-- Composite primary key on (player_id, season, week).
-- Stat columns are sparse by design — passing stats are null for non-QBs, etc.
-- player_id is a GSIS ID that maps to players.gsis_id.

CREATE TABLE IF NOT EXISTS player_stats (
    player_id                   VARCHAR(20) NOT NULL,
    player_name                 VARCHAR(60),
    player_display_name         VARCHAR(60),
    position                    VARCHAR(10),
    position_group              VARCHAR(10),
    headshot_url                VARCHAR(255),
    season                      INT NOT NULL,
    week                        INT NOT NULL,
    season_type                 VARCHAR(10) NOT NULL,
    game_id                     VARCHAR(30),
    team                        VARCHAR(5),
    opponent_team               VARCHAR(5),
    -- Passing
    completions                 INT,
    attempts                    INT,
    passing_yards               INT,
    passing_tds                 INT,
    passing_interceptions       INT,
    sacks_suffered              INT,
    sack_yards_lost             INT,
    sack_fumbles                INT,
    sack_fumbles_lost           INT,
    passing_air_yards           INT,
    passing_yards_after_catch   INT,
    passing_first_downs         INT,
    passing_epa                 REAL,
    passing_cpoe                REAL,
    passing_2pt_conversions     INT,
    pacr                        REAL,
    -- Rushing
    carries                     INT,
    rushing_yards               INT,
    rushing_tds                 INT,
    rushing_fumbles             INT,
    rushing_fumbles_lost        INT,
    rushing_first_downs         INT,
    rushing_epa                 REAL,
    rushing_2pt_conversions     INT,
    -- Receiving
    receptions                  INT,
    targets                     INT,
    receiving_yards             INT,
    receiving_tds               INT,
    receiving_fumbles           INT,
    receiving_fumbles_lost      INT,
    receiving_air_yards         INT,
    receiving_yards_after_catch INT,
    receiving_first_downs       INT,
    receiving_epa               REAL,
    receiving_2pt_conversions   INT,
    racr                        REAL,
    target_share                REAL,
    air_yards_share             REAL,
    wopr                        REAL,
    -- Special teams
    special_teams_tds           INT,
    -- Defense
    def_tackles_solo            INT,
    def_tackles_with_assist     INT,
    def_tackle_assists          INT,
    def_tackles_for_loss        INT,
    def_tackles_for_loss_yards  INT,
    def_fumbles_forced          INT,
    def_sacks                   REAL,
    def_sack_yards              REAL,
    def_qb_hits                 INT,
    def_interceptions           INT,
    def_interception_yards      INT,
    def_pass_defended           INT,
    def_tds                     INT,
    def_fumbles                 INT,
    def_safeties                INT,
    -- Miscellaneous
    misc_yards                  INT,
    fumble_recovery_own         INT,
    fumble_recovery_yards_own   INT,
    fumble_recovery_opp         INT,
    fumble_recovery_yards_opp   INT,
    fumble_recovery_tds         INT,
    penalties                   INT,
    penalty_yards               INT,
    -- Returns
    punt_returns                INT,
    punt_return_yards           INT,
    kickoff_returns             INT,
    kickoff_return_yards        INT,
    -- Kicking
    fg_made                     INT,
    fg_att                      INT,
    fg_missed                   INT,
    fg_blocked                  INT,
    fg_long                     REAL,
    fg_pct                      REAL,
    fg_made_0_19                INT,
    fg_made_20_29               INT,
    fg_made_30_39               INT,
    fg_made_40_49               INT,
    fg_made_50_59               INT,
    fg_made_60_                 INT,
    fg_missed_0_19              INT,
    fg_missed_20_29             INT,
    fg_missed_30_39             INT,
    fg_missed_40_49             INT,
    fg_missed_50_59             INT,
    fg_missed_60_               INT,
    fg_made_list                VARCHAR(100),
    fg_missed_list              VARCHAR(100),
    fg_blocked_list             VARCHAR(100),
    fg_made_distance            INT,
    fg_missed_distance          INT,
    fg_blocked_distance         INT,
    pat_made                    INT,
    pat_att                     INT,
    pat_missed                  INT,
    pat_blocked                 INT,
    pat_pct                     REAL,
    gwfg_made                   INT,
    gwfg_att                    INT,
    gwfg_missed                 INT,
    gwfg_blocked                INT,
    gwfg_distance               INT,
    -- Fantasy
    fantasy_points              REAL,
    fantasy_points_ppr          REAL,
    created_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (player_id, season, week)
);